### ISSUE TITLE
Crash When Opening AbyssalBlock

### ISSUE THREAD

**Issue by Morpheus1101** [Shinoow/AbyssalBlocks#1]
Mod loads in my pack aok, world gen is ok and up untill now, opening the blocks has been fine, but this time around it had a crash @ http://pastebin.com/QnAEY3Q8

**Comment by Shinoow** [comment]
It seems that the schematic placing trigger still attempts to place down a schematic even when the schematics folder actually is empty.

**Comment by Tedyhere** [comment]
Getting same issue here.
http://pastebin.com/BEiVPdBN  1.7.10 version

**Comment by Shinoow** [comment]
Not that many changes across the branches (at this point), so that bug is pretty much universal. Will be dealt with in the next release.
