### ISSUE TITLE
Opening an AbyssalBlock crashed

### ISSUE THREAD

**Issue by APolarBaer** [Shinoow/AbyssalBlocks#2]
i have no clue if its related to the other issue posted so im sorry if this is duplicate but heres the crashlog
[crash-2016-06-06_11.48.13-client.txt](https://github.com/Shinoow/AbyssalBlocks/files/300777/crash-2016-06-06_11.48.13-client.txt)

**Comment by APolarBaer** [comment]
logged back into the world and there was just an ender pearl
lol

**Comment by Shinoow** [comment]
Yeah, it's actually the same thing as the other issue (even when told there's no schematics loaded, it keeps trying to load schematics).

**Comment by Shinoow** [comment]
Since I'm working on an update for AbyssalCraft that will revamp a lot of internal things (some which this mod is using) there will be an update out for AbyssalBlocks shortly after that which will also patch this up.

**Comment by APolarBaer** [comment]
Okay, sorry again for the duplicate  Shinoow

**Comment by Shinoow** [comment]
It's fine, I don't get duplicate bug reports that often.
